% Need to be modified
ExportChannel_SignalNames =     [   "rho_ref",...                                               % 1024
                                    "rho_previewed",...                                         % 1025
                                    "Sortie_7",...                                              % 1026
                                    "ExportChannel1027",...                                     % 1027
                                    "ExportChannel1028",...                                     % 1028
                                    "RoadX",...                                                 % 1029
                                    "RoadY",...                                                 % 1030
                                    "ExportChannel1031",...                                     % 1031
                                    "Vehicle_X",...                                             % 1032
                                    "Vehicle_Y",...                                             % 1033
                                    "Y_Road",...                                                % 1034
                                    "ExportChannel035",...                                      % 1035
                                    "ExportChannel036",...                                      % 1036
                                    "ExportChannel037",...                                      % 1037
                                    "ExportChannel038",...                                      % 1038
                                    "ExportChannel039",...                                      % 1039
                                    "curvilinear_abs",...                                       % 1040
                                    "Heading_SCANeR",...                                        % 1041
                                    "TLCP",...                                                  % 1042    
                                    "Tc",...                                                    % 30
                                    "vx",...                                                    % 31
                                    "a_lat",...                                                 % 32    
                                    "T_Pilot_inversed",...                                      % 33
                                    "Heading",...                                               % 34
                                    "Beta",...                                                  % 35
                                    "r",...                                                     % 36
                                    "Psi_L_1",...                                               % 37
                                    "Y_L_2",...                                                 % 38
                                    "delta_d",...                                               % 39
                                    "delta_d_pt",...                                            % 40
                                    "T_VO",...                                                  % 41
                                    "T_VU_inversed",...                                         % 42
                                    "T_Effective",...                                           % 43
                                    "T_Target",...                                              % 44
                                    "Tc_FB",...                                                 % 45
                                    "Tc_FF",...                                                 % 46
                                    "beta_diff",...                                             % 47
                                    "r_diff",...                                                % 48
                                    "psi_L_diff",...                                            % 49
                                    "y_L_diff",...                                              % 50
                                    "delta_d_diff",...                                          % 51
                                    "delta_d_pt_diff",...                                       % 52
                                    "delta_d_VO",...                                            % 53
                                    "delta_d_pt_VO",...                                         % 54
                                    "Psi_L",...                                                 % 55
                                    "Y_L",...                                                   % 56
                                    "Road_angle",...                                            % 57
                                    "beta_VR",...                                               % 58
                                    "r_VR",...                                                  % 59
                                    "psi_L_VR",...                                              % 60
                                    "y_L_VR",...                                                % 61
                                    "delta_d_VR",...                                            % 62
                                    "delta_d_pt_VR",...                                         % 63
                                    "Precompensation_FF",...                                    % 64
                                    "FIR_FF",...                                                % 65
                                    "vy",...                                                    % 66
                                    "Psi_L_VU",...                                              % 67
                                    "Y_L_calcul",...                                            % 68
                                    "alpha",...                                                 % 69
                                    "Psi_L_calcul",...                                          % 70
                                    "RoadAngle",...                                             % 71
                                    "delta_f",...                                               % 72
                                    "Heading_1",...                                             % 73
                                    "road_abscissa",...                                         % 74
                                    "DistanceOnTraj",...                                        % 75
                                    "Heading_SCANeR",...                                        % 76
                                    "Psi_L_calcul_filtre",...                                   % 77
                                    "Etat",...                                                  % 78
                                    "Transition",...                                            % 79
                                    "SetAutonomous",...                                         % 20000
                                    "LastTimeMarker"];